name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    tags: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: Checkout code
      with:
        ref: ${{ github.ref_name }}
        
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ${{ github.repository }}
          ghcr.io/${{ github.repository }}
        tags: |
          type=schedule
          type=ref,event=branch
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          
    - name: dockerhub Login
      uses: docker/login-action@v2.1.0
      with:
        username:  ${{ github.actor }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: ghcr Login
      uses: docker/login-action@v2.1.0
      with:
        registry: ghcr.io
        username:  ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - uses: docker/build-push-action@v4.1.0
      name: Build and push image
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

