name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    tags: [ '*' ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: Checkout code
      with:
        ref: ${{ github.ref_name }}
        
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        registry: ghcr.io
        username:  ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - uses: docker/build-push-action@v4.0.0
      name: Build and push image
      with:
        context: .
        push: true
        tags:
        - ghcr.io/${{ github.repository }}:latest
        - ghcr.io/${{ github.repository }}:${{ github.ref_name }}
